site_name: Memento Dev

nav:
  - Accueil: index.md
  - DWWM:
      - Millésime 2023: dwwm/2023/index.md
      - Millésime 2018:
          - Sommaire: dwwm/2018/index.md
          - CP 1: dwwm/2018/cp-1-maquetter-une-application.md
          - CP 2: dwwm/2018/cp-2-realiser-une-interface-utilisateur-web-statique-et-adaptable.md
          - CP 3: dwwm/2018/cp-3-developper-une-interface-utilisateur-web-dynamique.md
          - CP 4: dwwm/2018/cp-4-realiser-une-interface-utilisateur-avec-une-solution-de-gestion-de-contenu-ou-e-commerce.md
          - CP 5: dwwm/2018/cp-5-creer-une-base-de-donnees.md
          - CP 6: dwwm/2018/cp-6-developper-les-composants-d-acces-aux-donnees.md
          - CP 7: dwwm/2018/cp-7-developper-la-partie-back-end-d-une-application-web-ou-web-mobile.md
          - CP 8: dwwm/2018/cp-8-elaborer-et-mettre-en-oeuvre-des-composants-dans-une-application-de-gestion-de-contenu-ou-e-commerce.md
  - Ressources:
      - Front-end: ressources/front-end/index.md
      - Back-end: ressources/back-end/index.md
      - DevOps: ressources/devops/index.md
      - Divers: ressources/divers/index.md
  - A propos: a-propos.md

extra_css:
  - extra.css

theme:
  language: fr
  icon:
    admonition:
      heart: octicons/heart-16
  name: material
  favicon: assets/favicon.webp
  logo: assets/logo.webp
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Passer en mode clair

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: >
  <p>
    Créé avec ❤️ par <a href="https://gauthierdaniels.fr/fr" target="_blank" rel="noreferrer noopener">Gauthier Daniels</a>
  </p>

extra:
  generator: false
